# Generated by Django 3.2 on 2021-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=10)),
                ('state', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
