# Generated by Django 3.2 on 2021-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
