# Generated by Django 3.2 on 2021-09-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=20)),
                ('radio', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.user')),
            ],
        ),
    ]
