# Generated by Django 3.2 on 2021-05-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_order_details_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='payment_mode',
            field=models.CharField(choices=[(0, 'cash on delivery'), (1, 'online payment')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='state',
            field=models.CharField(choices=[(0, 'Uttar Pradesh'), (1, 'Madhya Pradesh'), (2, 'Jharkhand'), (3, 'Bihar')], default=0, max_length=20),
        ),
    ]
