# Generated by Django 3.2 on 2021-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210522_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[(0, 'Uttar Pradesh'), (1, 'Madhya Pradesh'), (2, 'Jharkhand'), (3, 'Bihar')], default=0, max_length=20)),
                ('radio', models.CharField(choices=[(0, 'cash on delivery'), (1, 'online payment')], default=0, max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order_details',
        ),
    ]
