# Generated by Django 3.2 on 2021-09-13 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
