# Generated by Django 3.2 on 2021-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
