# Generated by Django 3.2 on 2021-09-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='image',
            field=models.ImageField(upload_to='productsImage/'),
        ),
    ]
