# Generated by Django 3.2 on 2021-09-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20210918_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='Product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.product_detail'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='Quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
