# Generated by Django 3.2 on 2021-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20210920_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
