# Generated by Django 3.2 on 2021-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20210921_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='selling_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
